### ISSUE TITLE
Homebridge via Docker issue

### ISSUE THREAD

**Issue by boostdd** [beele/HomebridgeLgSmartThinqAirco#1]
Hello Kevin,

I hope you can help me with my issue.

I have Homebridge installed via Docker on an Unraid server. I can install the "Homebridge Smart Thinq LG Airco" plugin, and navigate to /usr/lib/node_modules/homebridge-lg-airco/resources/wideq, however, when I execute the phyton3 command, I get no response.

My other Homebridge plugins/accessories appear to be working fine.

Homebridge Container: https://github.com/SiwatINC/homebridge_gui_unraid
Unraid Version: 6.7.3-rc2 

I've attached some screenshots, any help is greatly appreciated! 

Thank you for your time!

<img width="939" alt="Screen Shot 2019-08-14 at 10 03 09 PM" src="https://user-images.githubusercontent.com/46472627/63068387-fee6c880-bee0-11e9-8ad3-8adc9eea706d.png">
<img width="947" alt="Screen Shot 2019-08-14 at 10 05 09 PM" src="https://user-images.githubusercontent.com/46472627/63068388-fee6c880-bee0-11e9-99bf-11f2c5a2d86a.png">

**Comment by beele** [comment]
That is weird, can you verify that the python 3 instance is working correctly? by opening an interactive shell or printing the version

**Comment by kaiatkins** [comment]
I am using docker with WD PR4100

the error I am getting when home bridge loads:

[8/28/2019, 10:35:23 AM] Homebridge is running on port 53998.
Traceback (most recent call last):
  File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/example.py", line 1, in <module>
    import wideq
  File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq/__init__.py", line 3, in <module>
    from .core import *  # noqa
  File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq/core.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'



When running root@PR4100 wideq # python example.py -c "US" -l "en-US" -s "wideq_state.json" l
s
  File "example.py", line 88
SyntaxError: Non-ASCII character '\xc2' in file example.py on line 88, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
root@PR4100 wideq # python3 
-sh: python3: not found
root@PR4100 wideq #

**Comment by beele** [comment]
Try with the latest version, I updated some stuff to make it work on python 3.7.x
