### ISSUE TITLE
Invalid Service Code

### ISSUE THREAD

**Issue by DavidFG75** [beele/HomebridgeLgSmartThinqAirco#13]
When I made the login in the page to get the url, the page show me this message:
        " Invalid Service Code"

Don't know what's wrong

Btw, this is the link it ask me to enter to get logged:
https://mx.m.lgaccount.com/login/sign_in?country=MX&language=es-MX&svcCode=SVC20

**Comment by beele** [comment]
Can you try by downloading wideq itself and running it from the terminal?
https://github.com/sampsyo/wideq
