### ISSUE TITLE
Aircon mode (heat, cool, auto)

### ISSUE THREAD

**Issue by carlittoer** [beele/HomebridgeLgSmartThinqAirco#2]
Hello ! 

Thank you so much for this plugin. My AC is working fine. However, it has only 1 mode (auto)

Is it possible to add heat, cool, auto ?

Also there is a fan speed setting in "settings". Is this functional ?

**Comment by rashmendis** [comment]
yes fan speed is working for me

**Comment by beele** [comment]
Doing the different modes is a real pain in the ass with homebridge. 
So for now only support for auto. You could try to set the temp higher than the room temp and see if it heats instead of cools.
