### ISSUE TITLE
Change Temperature values

### ISSUE THREAD

**Issue by rashmendis** [beele/HomebridgeLgSmartThinqAirco#3]
Great work @beele. Waiting this for so long. Btw Can I know how to change the min and max temperature? [ current min - 18 and max - 26 ]. I changed it from `coolingThresholdTemperatureCharac.setProps` and now it appears in the Home App but not sending to the A/C

**Comment by rashmendis** [comment]
Found the 2nd place which was homebridge-lg-airco/src/lg/wideq.js line 39

**Comment by beele** [comment]
I will try and make this configurable in the config.json in the future!
