### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by LAKY911** [beele/HomebridgeLgSmartThinqAirco#5]
Hi, I get this error message on Win 10.  Any way how to fix this? Thank you.

> Error: spawn python3 ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
>     at onErrorNT (internal/child_process.js:415:16)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by beele** [comment]
Do you have python3 installed and on the path?

**Comment by spalacioh** [comment]
same thing happened to me, I just fixed updating the code in wideq.js

//const pythonProcess = spawn('python', pythonArgs);
			
			const cp = require('child_process');
			const pythonProcess = cp.spwan('python', pythonArgs);
