### ISSUE TITLE
Zero temperature

### ISSUE THREAD

**Issue by alszaitsev** [beele/HomebridgeLgSmartThinqAirco#8]
First of all thanks for a great job!
I have some issues with the temperature - it shows 0,0, although ThinQ app shows it normal.
Device PC12SQ NSJ

![D3B214A4-CD34-42DE-8591-37DDF5386C06](https://user-images.githubusercontent.com/46629064/76357811-6e168500-6329-11ea-9a29-dd714413ab80.png)
![AC4BC537-4512-4FD1-A3B3-B5AA22D4E25F](https://user-images.githubusercontent.com/46629064/76357819-71aa0c00-6329-11ea-8c45-4b2f67a59074.png)

**Comment by danielbotka** [comment]
I have the same issue, receiving the following error in HomeBridge console
`
TypeError: Cannot read property 'substring' of undefined
    at parseMon (/homebridge/node_modules/homebridge-lg-airco/src/lg/wideq.js:122:42)
    at python.then (/homebridge/node_modules/homebridge-lg-airco/src/lg/wideq.js:25:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by danielbotka** [comment]
@piet2000 can you open a PR for your fix? Then @beele might merge it and will be updated for everyone who has the issue :)

**Comment by beele** [comment]
I'm starting work on a cleanup of my code and am also pulling in an updated version of wideq, hopefully this will resolve this issue

**Comment by beele** [comment]
I've published the new version, could you try with that? 
Please not that the config has changed! 
Follow the readme!
