### ISSUE TITLE
Question regarding connection to the internet.

### ISSUE THREAD

**Issue by Xenobreaker** [beele/HomebridgeLgSmartThinqAirco#9]
Hi! Thanks for your work on this. I've been considering buying an LG split inverter ac and using your plugin for Homebridge. I'm not sure if I should be asking this here or over at the WideQ github but I'm just curious if the plugin needs to always have a live connection to LG servers to function. I have all of my smart devices blocked from having internet access with all of my remote commands going through HomeKit only. I was just wondering if either the AC, the plugin or WideQ would need to have a consistent connection to LG servers to function after doing the initial setup for the device ID. Thanks again!

**Comment by beele** [comment]
It uses the LG API and requires an active internet connection.
